_extends: release-drafter-monorepo:.github/release-drafter.yml
name-template: 'modules/a/$RESOLVED_VERSION 🌈'
tag-template: 'modules/a/$RESOLVED_VERSION'
tag-prefix: 'modules/a/'
include-paths:
  - "modules/a"
