_extends: release-drafter-monorepo:.github/release-drafter.yml
name-template: 'modules/c/$RESOLVED_VERSION 🌈'
tag-template: 'modules/c/$RESOLVED_VERSION'
tag-prefix: 'modules/c/'
include-paths:
  - "modules/c"
