name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'modules/a/v'
categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - 'break'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📦 Dependencies'
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'dependencies'
    title:
      - '/deps/i'
      - '/chore(deps)/i'
  - label: 'bug'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    title:
      - '/feat/i'
      - '/enhancement/i'
  - label: 'break'
    title:
      - '/break/i'
