_extends: release-drafter-monorepo:.github/release-drafter.yml
name-template: 'modules/b/$RESOLVED_VERSION 🌈'
tag-template: 'modules/b/$RESOLVED_VERSION'
tag-prefix: 'modules/b/'
include-paths:
  - "modules/b"
